# Generated by Django 3.2.3 on 2021-05-25 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommends.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='movies',
            field=models.ManyToManyField(related_name='recommend_words', through='recommends.KM', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(related_name='keywords', to=settings.AUTH_USER_MODEL),
        ),
    ]
