# Generated by Django 3.2.3 on 2021-05-24 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(related_name='recommend_words', to='movies.Movie')),
                ('users', models.ManyToManyField(related_name='keywords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
